# Generated by Django 4.2.5 on 2023-12-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
    ]
